[package]
name = "rust_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_engine"
crate-type = ["cdylib"]

[dependencies]
crossbeam-channel = "0.5.15"
pyo3 = "0.25.0"
